name = "Catden Pack"
author = "-"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b4751f0c9f09c6948af2caa1950ff3dd3eeb0125f31217a6a1e837e0da031ef"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
