name = "Catden Pack"
author = "-"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf0da67b6ddca805f9f27acfef1392bf0ccae6c7452b3bf60884066e6279fc7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
